create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  full_name text,
  bio text,
  avatar_url text,
  role text not null default 'member' check (role in ('visitor', 'member', 'contributor', 'historian', 'moderator', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid references public.profiles(id) on delete set null,
  category_id bigint references public.categories(id) on delete set null,
  title text not null,
  content text not null,
  media_url text,
  is_pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  author_id uuid references public.profiles(id) on delete set null,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_likes (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create table if not exists public.memories (
  id uuid primary key default gen_random_uuid(),
  author_id uuid references public.profiles(id) on delete set null,
  category_id bigint references public.categories(id) on delete set null,
  title text not null,
  story text not null,
  era_label text,
  location text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.memory_media (
  id uuid primary key default gen_random_uuid(),
  memory_id uuid not null references public.memories(id) on delete cascade,
  uploader_id uuid references public.profiles(id) on delete set null,
  bucket text not null default 'memory-archive',
  file_path text not null,
  media_type text not null default 'image',
  caption text,
  created_at timestamptz not null default now()
);

create table if not exists public.ideas (
  id uuid primary key default gen_random_uuid(),
  author_id uuid references public.profiles(id) on delete set null,
  category_id bigint references public.categories(id) on delete set null,
  title text not null,
  description text not null,
  status text not null default 'open' check (status in ('open', 'planned', 'implemented', 'archived')),
  votes_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.idea_votes (
  id uuid primary key default gen_random_uuid(),
  idea_id uuid not null references public.ideas(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (idea_id, user_id)
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid references public.profiles(id) on delete set null,
  target_type text not null check (target_type in ('post', 'comment', 'memory', 'idea')),
  target_id uuid not null,
  reason text not null,
  status text not null default 'open' check (status in ('open', 'reviewed', 'resolved', 'dismissed')),
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text not null,
  link text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at before update on public.posts
for each row execute function public.set_updated_at();

drop trigger if exists comments_set_updated_at on public.comments;
create trigger comments_set_updated_at before update on public.comments
for each row execute function public.set_updated_at();

drop trigger if exists memories_set_updated_at on public.memories;
create trigger memories_set_updated_at before update on public.memories
for each row execute function public.set_updated_at();

drop trigger if exists ideas_set_updated_at on public.ideas;
create trigger ideas_set_updated_at before update on public.ideas
for each row execute function public.set_updated_at();

create or replace function public.sync_idea_votes_count()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    update public.ideas
    set votes_count = votes_count + 1
    where id = new.idea_id;
    return new;
  elsif tg_op = 'DELETE' then
    update public.ideas
    set votes_count = greatest(votes_count - 1, 0)
    where id = old.idea_id;
    return old;
  end if;
  return null;
end;
$$;

drop trigger if exists idea_votes_count_trigger on public.idea_votes;
create trigger idea_votes_count_trigger
after insert or delete on public.idea_votes
for each row execute function public.sync_idea_votes_count();

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    'member'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
after insert on auth.users
for each row execute function public.handle_new_user_profile();

create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = uid
      and role in ('moderator', 'admin')
  );
$$;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.post_likes enable row level security;
alter table public.memories enable row level security;
alter table public.memory_media enable row level security;
alter table public.ideas enable row level security;
alter table public.idea_votes enable row level security;
alter table public.reports enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "profiles_public_read" on public.profiles;
create policy "profiles_public_read" on public.profiles
for select using (true);

drop policy if exists "profiles_insert_self" on public.profiles;
create policy "profiles_insert_self" on public.profiles
for insert with check (auth.uid() = id);

drop policy if exists "profiles_update_self_or_admin" on public.profiles;
create policy "profiles_update_self_or_admin" on public.profiles
for update using (auth.uid() = id or public.is_admin(auth.uid()))
with check (auth.uid() = id or public.is_admin(auth.uid()));

drop policy if exists "categories_public_read" on public.categories;
create policy "categories_public_read" on public.categories
for select using (true);

drop policy if exists "categories_admin_manage" on public.categories;
create policy "categories_admin_manage" on public.categories
for all using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "posts_public_read" on public.posts;
create policy "posts_public_read" on public.posts
for select using (true);

drop policy if exists "posts_create_authenticated" on public.posts;
create policy "posts_create_authenticated" on public.posts
for insert with check (auth.uid() = author_id);

drop policy if exists "posts_update_owner_or_admin" on public.posts;
create policy "posts_update_owner_or_admin" on public.posts
for update using (auth.uid() = author_id or public.is_admin(auth.uid()))
with check (auth.uid() = author_id or public.is_admin(auth.uid()));

drop policy if exists "posts_delete_owner_or_admin" on public.posts;
create policy "posts_delete_owner_or_admin" on public.posts
for delete using (auth.uid() = author_id or public.is_admin(auth.uid()));

drop policy if exists "comments_public_read" on public.comments;
create policy "comments_public_read" on public.comments
for select using (true);

drop policy if exists "comments_create_authenticated" on public.comments;
create policy "comments_create_authenticated" on public.comments
for insert with check (auth.uid() = author_id);

drop policy if exists "comments_update_owner_or_admin" on public.comments;
create policy "comments_update_owner_or_admin" on public.comments
for update using (auth.uid() = author_id or public.is_admin(auth.uid()))
with check (auth.uid() = author_id or public.is_admin(auth.uid()));

drop policy if exists "comments_delete_owner_or_admin" on public.comments;
create policy "comments_delete_owner_or_admin" on public.comments
for delete using (auth.uid() = author_id or public.is_admin(auth.uid()));

drop policy if exists "post_likes_public_read" on public.post_likes;
create policy "post_likes_public_read" on public.post_likes
for select using (true);

drop policy if exists "post_likes_create_authenticated" on public.post_likes;
create policy "post_likes_create_authenticated" on public.post_likes
for insert with check (auth.uid() = user_id);

drop policy if exists "post_likes_delete_owner_or_admin" on public.post_likes;
create policy "post_likes_delete_owner_or_admin" on public.post_likes
for delete using (auth.uid() = user_id or public.is_admin(auth.uid()));

drop policy if exists "memories_read_public_or_owner_or_admin" on public.memories;
create policy "memories_read_public_or_owner_or_admin" on public.memories
for select using (
  status = 'approved'
  or author_id = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists "memories_create_authenticated" on public.memories;
create policy "memories_create_authenticated" on public.memories
for insert with check (auth.uid() = author_id);

drop policy if exists "memories_update_owner_or_admin" on public.memories;
create policy "memories_update_owner_or_admin" on public.memories
for update using (auth.uid() = author_id or public.is_admin(auth.uid()))
with check (auth.uid() = author_id or public.is_admin(auth.uid()));

drop policy if exists "memories_delete_owner_or_admin" on public.memories;
create policy "memories_delete_owner_or_admin" on public.memories
for delete using (auth.uid() = author_id or public.is_admin(auth.uid()));

drop policy if exists "memory_media_public_read_by_memory_visibility" on public.memory_media;
create policy "memory_media_public_read_by_memory_visibility" on public.memory_media
for select using (
  exists (
    select 1
    from public.memories m
    where m.id = memory_media.memory_id
      and (
        m.status = 'approved'
        or m.author_id = auth.uid()
        or public.is_admin(auth.uid())
      )
  )
);

drop policy if exists "memory_media_create_authenticated" on public.memory_media;
create policy "memory_media_create_authenticated" on public.memory_media
for insert with check (auth.uid() = uploader_id);

drop policy if exists "memory_media_delete_owner_or_admin" on public.memory_media;
create policy "memory_media_delete_owner_or_admin" on public.memory_media
for delete using (auth.uid() = uploader_id or public.is_admin(auth.uid()));

drop policy if exists "ideas_public_read" on public.ideas;
create policy "ideas_public_read" on public.ideas
for select using (true);

drop policy if exists "ideas_create_authenticated" on public.ideas;
create policy "ideas_create_authenticated" on public.ideas
for insert with check (auth.uid() = author_id);

drop policy if exists "ideas_update_owner_or_admin" on public.ideas;
create policy "ideas_update_owner_or_admin" on public.ideas
for update using (auth.uid() = author_id or public.is_admin(auth.uid()))
with check (auth.uid() = author_id or public.is_admin(auth.uid()));

drop policy if exists "ideas_delete_owner_or_admin" on public.ideas;
create policy "ideas_delete_owner_or_admin" on public.ideas
for delete using (auth.uid() = author_id or public.is_admin(auth.uid()));

drop policy if exists "idea_votes_public_read" on public.idea_votes;
create policy "idea_votes_public_read" on public.idea_votes
for select using (true);

drop policy if exists "idea_votes_create_authenticated" on public.idea_votes;
create policy "idea_votes_create_authenticated" on public.idea_votes
for insert with check (auth.uid() = user_id);

drop policy if exists "idea_votes_delete_owner_or_admin" on public.idea_votes;
create policy "idea_votes_delete_owner_or_admin" on public.idea_votes
for delete using (auth.uid() = user_id or public.is_admin(auth.uid()));

drop policy if exists "reports_read_owner_or_admin" on public.reports;
create policy "reports_read_owner_or_admin" on public.reports
for select using (reporter_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists "reports_create_authenticated" on public.reports;
create policy "reports_create_authenticated" on public.reports
for insert with check (reporter_id = auth.uid());

drop policy if exists "reports_admin_manage" on public.reports;
create policy "reports_admin_manage" on public.reports
for update using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "notifications_owner_or_admin_read" on public.notifications;
create policy "notifications_owner_or_admin_read" on public.notifications
for select using (user_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists "notifications_owner_or_admin_manage" on public.notifications;
create policy "notifications_owner_or_admin_manage" on public.notifications
for all using (user_id = auth.uid() or public.is_admin(auth.uid()))
with check (user_id = auth.uid() or public.is_admin(auth.uid()));

insert into storage.buckets (id, name, public)
values
  ('avatars', 'avatars', true),
  ('post-media', 'post-media', true),
  ('memory-archive', 'memory-archive', true)
on conflict (id) do nothing;

drop policy if exists "avatars_public_read" on storage.objects;
create policy "avatars_public_read" on storage.objects
for select using (bucket_id = 'avatars');

drop policy if exists "avatars_upload_own" on storage.objects;
create policy "avatars_upload_own" on storage.objects
for insert to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "post_media_public_read" on storage.objects;
create policy "post_media_public_read" on storage.objects
for select using (bucket_id = 'post-media');

drop policy if exists "post_media_upload_authenticated" on storage.objects;
create policy "post_media_upload_authenticated" on storage.objects
for insert to authenticated
with check (bucket_id = 'post-media');

drop policy if exists "memory_archive_public_read" on storage.objects;
create policy "memory_archive_public_read" on storage.objects
for select using (bucket_id = 'memory-archive');

drop policy if exists "memory_archive_upload_own" on storage.objects;
create policy "memory_archive_upload_own" on storage.objects
for insert to authenticated
with check (bucket_id = 'memory-archive' and (storage.foldername(name))[1] = auth.uid()::text);

